### ISSUE TITLE
Vertically align header link anchors and adapt to title size

### ISSUE THREAD

**Issue by IgnaceMaes** [ember-learn/guidemaker-ember-template#183]
Currently the header anchor links are the same for every title. This makes them feel small-ish on large titles, but mostly huge on small titles. This could be adapted to be made smaller for smaller titles.

A side effect of this is that it also isn't properly vertically aligned.

Example: https://guidemaker-ember-template.netlify.app/release/examples/

<img width="267" alt="image" src="https://github.com/ember-learn/guidemaker-ember-template/assets/10243652/d6be4086-e8c9-4133-a415-139873a38cc8">

**Comment by kennstenicht** [comment]
@IgnaceMaes I think this looks better: https://deploy-preview-200--guidemaker-ember-template.netlify.app/release/examples

I don't think we have an anchor link on h1 headlines, because the article headlines don't have anchor links and we should noch use h1 inside the content to avoid multiple h1 per page.

**Comment by IgnaceMaes** [comment]
Looks way better!

> we should noch use h1 inside the content to avoid multiple h1 per page.

Exactly. We have an open issue for that as well to enforce this with markdown linting: https://github.com/ember-learn/guides-source/issues/2015
